name: Rust

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - 'tests/**.rs'
      - 'Cargo.toml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - 'tests/**.rs'
      - 'Cargo.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Unix
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain nightly
             echo ::add-path::$HOME/.cargo/bin
        fi

    - name: Install embedded targets
      run: |
        rustup target add riscv32imc-unknown-none-elf
        rustup target add riscv32imac-unknown-none-elf

    - name: Install Miri
      run: |
        rustup toolchain install nightly
        rustup +nightly component add miri

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Check polyfill on target without atomics
      run: cargo build --features critical-section-polyfill --target riscv32imc-unknown-none-elf

    - name: Check polyfill on target with atomics
      run: cargo build --features critical-section-polyfill --target riscv32imac-unknown-none-elf

    - name: Check build
      run: cargo clippy

    - name: Test
      run: cargo test

    - name: Test Polyfill
      run: cargo test --features critical-section-polyfill

    - name: Miri Test
      run: |
          cargo +nightly miri test
          cargo +nightly  miri test --release
